version: '3.8'
services:
  app:
    build: .
    container_name: qcadastro_app
    restart: always
    environment:
      - PORT=8000
      - CENPROT_CERT_PATH=/app/etc/qcadastro/certs/QUALITY_TRANSPORTES_E_ENTREGAS_RAPIDAS_LTDA06321409000196.pfx
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./etc:/app/etc

  nginx:
    image: nginx:alpine
    container_name: qcadastro_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./uploads:/app/uploads
    depends_on:
      - app
    restart: always
