FROM node:23-alpine

# Criar diretório da aplicação
WORKDIR /app

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar código-fonte
COPY . .

# Construir a aplicação
RUN npm run build

# Expor porta
EXPOSE 8000

# Comando para iniciar a aplicação
CMD ["npm", "run", "start:prod"]